document.writeln("<section id=\'footer\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-md-12\'>");
document.writeln("                    ");
document.writeln("                </div>");
document.writeln("                <div class=\'col-md-6\'>");
document.writeln("                    <address>");
document.writeln("                        <svg class=\'icon text-danger\' aria-hidden=\'true\'>");
document.writeln("                            <use xlink:href=\'#icon-diqiu\'></use>");
document.writeln("                        </svg> <strong>重庆海顿科技有限公司 </strong><br>");
document.writeln("                        <svg class=\'icon\' aria-hidden=\'true\'>");
document.writeln("                            <use xlink:href=\'#icon-shouji\'></use>");
document.writeln("                        </svg>");
document.writeln("                        <abbr title=\'Phone\'>联系人：向先生&nbsp;&nbsp;手机：1363-7777-865</abbr><br>");
document.writeln("                        <svg class=\'icon text-primary\' aria-hidden=\'true\'>");
document.writeln("                            <use xlink:href=\'#icon-dianhua\'></use>");
document.writeln("                        </svg> 电话： 023-传真：023-<br />");
document.writeln("");
document.writeln("                        <svg class=\'icon\' aria-hidden=\'true\'>");
document.writeln("                            <use xlink:href=\'#icon-youjian\'></use>");
document.writeln("                        </svg><a href=\'mailto:#\'>20634529@qq.com</a><br />");
document.writeln("                        <svg class=\'icon\' aria-hidden=\'true\'>");
document.writeln("                            <use xlink:href=\'#icon-dizhi1\'></use>");
document.writeln("                        </svg>重庆市九龙坡区石桥铺华宇名都29号楼");
document.writeln("                    </address>");
document.writeln("");
document.writeln("");
document.writeln("                </div>");
document.writeln("                <div class=\'col-md-6\'>");
document.writeln("                    <!--底部导航-->");
document.writeln("                    <div class=\'row text-center\'>");
document.writeln("                        <ul class=\'list-inline\'>");
document.writeln("");
document.writeln("");
document.writeln("                            <!--<li><a href=\'javascript{void(0)}\'><i class=\'iconfont text-info\'>&#xe610;</i></a></li>");
document.writeln("                            <li><a href=\'javascript{void(0)}\'><i class=\'iconfont text-danger\'>&#xe611;</i></a></li>");
document.writeln("                            <li><a href=\'javascript{void(0)}\'><i class=\'iconfont text-primary\'>&#xe60f;</i></a></li>-->");
document.writeln("                            <li></li>");
document.writeln("                        </ul>");
document.writeln("");
document.writeln("");
document.writeln("                        <p>Copyright©&nbsp;&nbsp;All Rights Reserved&nbsp;&nbsp;<a href=\'http://www.cqgdbg.com/\'>海顿科技</a></p>");
document.writeln("                        <p>渝ICP备12002506号-5</p>");
document.writeln("                        <!--<a href=\'javascript{void(0)}\'></a>-->");
document.writeln("                    </div>");
document.writeln("                    <!--底部导航-->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </section>");