document.writeln("<nav class=\'navbar navbar-default navbar-fixed-top\'>");
document.writeln("");
document.writeln("        <div class=\'container\'>");
document.writeln("            <!--小屏幕按钮logo-->");
document.writeln("            <div class=\'navbar-header\'>");
document.writeln("                <button class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                    <span class=\'icon-bar\'></span>");
document.writeln("                </button>");
document.writeln("                <a class=\'navbar-brand\' href=\'javascript:void\'>");
document.writeln("                    <svg class=\'icon \' style=\'vertical-align: -0.55em;color:#ffffff\' aria-hidden=\'true\'>");
document.writeln("                        <use xlink:href=\'#icon-icon-test\'></use>");
document.writeln("                    </svg>海顿物联网管理系统");
document.writeln("");
document.writeln("                </a>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <!--导航-->");
document.writeln("");
document.writeln("            <div class=\'navbar-collapse collapse\'>");
document.writeln("                <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("");
document.writeln("                    <li>");
document.writeln("                        <a href=\'index.html' onFocus=\'this.blur()\'>");
document.writeln("                            <svg class=\'icon text-success\' aria-hidden=\'true\'>");
document.writeln("                                <use xlink:href=\'#icon-icon107\'></use>");
document.writeln("                            </svg>");
document.writeln("                            后台首页");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'UserAdmin.html\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            <svg class=\'icon text-success\' aria-hidden=\'true\'>");
document.writeln("                                <use xlink:href=\'#icon-chaxun\'></use>");
document.writeln("                            </svg>用户管理 <span class=\'caret\'></span>");
document.writeln("                        </a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'UserAdmin.html\'>用户管理</a></li>");
document.writeln("                           <!-- <li><a href=\'CenterCondition.html\'>热泵驱动型溶液恒温恒湿中央空调系统</a></li>");
document.writeln("                            <li><a href=\'WH-SG40.html\'>WH-SG40高速高精全自动硬质空心胶囊生产线</a></li>");
document.writeln("                            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("                            <li><a href=\'viscosity.html\'>在线粘度检测仪</a></li>");
document.writeln("                            <li role=\'separator\' class=\'divider\'></li>");
document.writeln("                            <li><a href=\'mould.html\'>高速高精胶囊生产线的配套模具</a></li>-->");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void\' onFocus=\'this.blur()\'>");
document.writeln("                            <svg class=\'icon text-success\' aria-hidden=\'true\'>");
document.writeln("                                <use xlink:href=\'#icon-bangongzidonghua\'></use>");
document.writeln("                            </svg>图像管理");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void\' onFocus=\'this.blur()\'>");
document.writeln("                            <svg class=\'icon text-success\' aria-hidden=\'true\'>");
document.writeln("                                <use xlink:href=\'#icon-tongjifenxi\'></use>");
document.writeln("                            </svg>统计分析");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'javascript:void\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                            <svg class=\'icon text-success\' aria-hidden=\'true\'>");
document.writeln("                                <use xlink:href=\'#icon-houtaiguanli\'></use>");
document.writeln("                            </svg>系统设置");
document.writeln("                        </a>");
document.writeln("                        <ul class=\'dropdown-menu\'>");
document.writeln("                            <li><a href=\'ProvinceAdmin.html\'>行政区域划分</a></li>");
document.writeln("                            <!--<li><a href=\'index_en.html\'>English</a></li>-->");
document.writeln("");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </nav>");